### ISSUE TITLE
Download feature not working on deployed website

### ISSUE THREAD

**Issue by kylegodbey** [The-Level-Density-Group/NLD_database_website#7]
The download CSV button does not appear to work on the https://nld.ascsn.net website. Looking at the server logs, there seems to be an error in the kaleido package's save functionality when it tries to write the figure.

**Comment by chirag167** [comment]
I have added a truncated requirements.txt file and removed the packages that I believe have nothing to do with the application. It still runs fine on my local machine.

**Comment by chirag167** [comment]
I ran the website on GitHub Codespaces. It looks like it is fixed now. Waiting for the website to come online.

**Comment by kylegodbey** [comment]
Works now! Problem was in packaging and in the docker image that was being built
